// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Kurrent.Pulumi.KurrentCloud
{
    [KurrentCloudResourceType("kurrentcloud:index/acl:Acl")]
    public partial class Acl : global::Pulumi.CustomResource
    {
        /// <summary>
        /// CIDR blocks allowed by the IP access list
        /// </summary>
        [Output("cidrBlocks")]
        public Output<ImmutableArray<ImmutableDictionary<string, object>>> CidrBlocks { get; private set; } = null!;

        /// <summary>
        /// Human-friendly name for the Acl
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Project ID
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;


        /// <summary>
        /// Create a Acl resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Acl(string name, AclArgs args, CustomResourceOptions? options = null)
            : base("kurrentcloud:index/acl:Acl", name, args ?? new AclArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Acl(string name, Input<string> id, AclState? state = null, CustomResourceOptions? options = null)
            : base("kurrentcloud:index/acl:Acl", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/kurrent-io",
                Aliases =
                {
                    new global::Pulumi.Alias { Type = "eventstorecloud:index/acl:Acl"},
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Acl resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Acl Get(string name, Input<string> id, AclState? state = null, CustomResourceOptions? options = null)
        {
            return new Acl(name, id, state, options);
        }
    }

    public sealed class AclArgs : global::Pulumi.ResourceArgs
    {
        [Input("cidrBlocks", required: true)]
        private InputList<ImmutableDictionary<string, object>>? _cidrBlocks;

        /// <summary>
        /// CIDR blocks allowed by the IP access list
        /// </summary>
        public InputList<ImmutableDictionary<string, object>> CidrBlocks
        {
            get => _cidrBlocks ?? (_cidrBlocks = new InputList<ImmutableDictionary<string, object>>());
            set => _cidrBlocks = value;
        }

        /// <summary>
        /// Human-friendly name for the Acl
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Project ID
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        public AclArgs()
        {
        }
        public static new AclArgs Empty => new AclArgs();
    }

    public sealed class AclState : global::Pulumi.ResourceArgs
    {
        [Input("cidrBlocks")]
        private InputList<ImmutableDictionary<string, object>>? _cidrBlocks;

        /// <summary>
        /// CIDR blocks allowed by the IP access list
        /// </summary>
        public InputList<ImmutableDictionary<string, object>> CidrBlocks
        {
            get => _cidrBlocks ?? (_cidrBlocks = new InputList<ImmutableDictionary<string, object>>());
            set => _cidrBlocks = value;
        }

        /// <summary>
        /// Human-friendly name for the Acl
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Project ID
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        public AclState()
        {
        }
        public static new AclState Empty => new AclState();
    }
}
