// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Kurrent.Pulumi.KurrentCloud
{
    [KurrentCloudResourceType("kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset")]
    public partial class ManagedClusterReplicaset : global::Pulumi.CustomResource
    {
        /// <summary>
        /// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        /// </summary>
        [Output("clusterId")]
        public Output<string> ClusterId { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// ID of the project that owns the parent managed cluster
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// Protection from accidental deletion. Delete is rejected by the API while this is true.
        /// </summary>
        [Output("protected")]
        public Output<bool?> Protected { get; private set; } = null!;

        /// <summary>
        /// Number of read-only replicas in the set (1 or 2)
        /// </summary>
        [Output("replicaCount")]
        public Output<int> ReplicaCount { get; private set; } = null!;

        /// <summary>
        /// Current status of the read-only replica set
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Last modification timestamp
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a ManagedClusterReplicaset resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ManagedClusterReplicaset(string name, ManagedClusterReplicasetArgs args, CustomResourceOptions? options = null)
            : base("kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset", name, args ?? new ManagedClusterReplicasetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ManagedClusterReplicaset(string name, Input<string> id, ManagedClusterReplicasetState? state = null, CustomResourceOptions? options = null)
            : base("kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/kurrent-io",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ManagedClusterReplicaset resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ManagedClusterReplicaset Get(string name, Input<string> id, ManagedClusterReplicasetState? state = null, CustomResourceOptions? options = null)
        {
            return new ManagedClusterReplicaset(name, id, state, options);
        }
    }

    public sealed class ManagedClusterReplicasetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        /// </summary>
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        /// <summary>
        /// ID of the project that owns the parent managed cluster
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// Protection from accidental deletion. Delete is rejected by the API while this is true.
        /// </summary>
        [Input("protected")]
        public Input<bool>? Protected { get; set; }

        /// <summary>
        /// Number of read-only replicas in the set (1 or 2)
        /// </summary>
        [Input("replicaCount", required: true)]
        public Input<int> ReplicaCount { get; set; } = null!;

        public ManagedClusterReplicasetArgs()
        {
        }
        public static new ManagedClusterReplicasetArgs Empty => new ManagedClusterReplicasetArgs();
    }

    public sealed class ManagedClusterReplicasetState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        /// </summary>
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// ID of the project that owns the parent managed cluster
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// Protection from accidental deletion. Delete is rejected by the API while this is true.
        /// </summary>
        [Input("protected")]
        public Input<bool>? Protected { get; set; }

        /// <summary>
        /// Number of read-only replicas in the set (1 or 2)
        /// </summary>
        [Input("replicaCount")]
        public Input<int>? ReplicaCount { get; set; }

        /// <summary>
        /// Current status of the read-only replica set
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Last modification timestamp
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public ManagedClusterReplicasetState()
        {
        }
        public static new ManagedClusterReplicasetState Empty => new ManagedClusterReplicasetState();
    }
}
