// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kurrentcloud

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/kurrent-io/pulumi-kurrentcloud/sdk/go/kurrentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "kurrentcloud:index/aWSCloudWatchLogsIntegration:AWSCloudWatchLogsIntegration":
		r = &AWSCloudWatchLogsIntegration{}
	case "kurrentcloud:index/aWSCloudWatchMetricsIntegration:AWSCloudWatchMetricsIntegration":
		r = &AWSCloudWatchMetricsIntegration{}
	case "kurrentcloud:index/acl:Acl":
		r = &Acl{}
	case "kurrentcloud:index/integration:Integration":
		r = &Integration{}
	case "kurrentcloud:index/managedCluster:ManagedCluster":
		r = &ManagedCluster{}
	case "kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset":
		r = &ManagedClusterReplicaset{}
	case "kurrentcloud:index/network:Network":
		r = &Network{}
	case "kurrentcloud:index/peering:Peering":
		r = &Peering{}
	case "kurrentcloud:index/project:Project":
		r = &Project{}
	case "kurrentcloud:index/scheduledBackup:ScheduledBackup":
		r = &ScheduledBackup{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:kurrentcloud" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/aWSCloudWatchLogsIntegration",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/aWSCloudWatchMetricsIntegration",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/acl",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/integration",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/managedCluster",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/managedClusterReplicaset",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/peering",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"kurrentcloud",
		"index/scheduledBackup",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"kurrentcloud",
		&pkg{version},
	)
}
