// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kurrentcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/kurrent-io/pulumi-kurrentcloud/sdk/go/kurrentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ManagedClusterReplicaset struct {
	pulumi.CustomResourceState

	// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// Creation timestamp
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// ID of the project that owns the parent managed cluster
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Protection from accidental deletion. Delete is rejected by the API while this is true.
	Protected pulumi.BoolPtrOutput `pulumi:"protected"`
	// Number of read-only replicas in the set (1 or 2)
	ReplicaCount pulumi.IntOutput `pulumi:"replicaCount"`
	// Current status of the read-only replica set
	Status pulumi.StringOutput `pulumi:"status"`
	// Last modification timestamp
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewManagedClusterReplicaset registers a new resource with the given unique name, arguments, and options.
func NewManagedClusterReplicaset(ctx *pulumi.Context,
	name string, args *ManagedClusterReplicasetArgs, opts ...pulumi.ResourceOption) (*ManagedClusterReplicaset, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.ReplicaCount == nil {
		return nil, errors.New("invalid value for required argument 'ReplicaCount'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ManagedClusterReplicaset
	err := ctx.RegisterResource("kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetManagedClusterReplicaset gets an existing ManagedClusterReplicaset resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetManagedClusterReplicaset(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ManagedClusterReplicasetState, opts ...pulumi.ResourceOption) (*ManagedClusterReplicaset, error) {
	var resource ManagedClusterReplicaset
	err := ctx.ReadResource("kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ManagedClusterReplicaset resources.
type managedClusterReplicasetState struct {
	// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
	ClusterId *string `pulumi:"clusterId"`
	// Creation timestamp
	CreatedAt *string `pulumi:"createdAt"`
	// ID of the project that owns the parent managed cluster
	ProjectId *string `pulumi:"projectId"`
	// Protection from accidental deletion. Delete is rejected by the API while this is true.
	Protected *bool `pulumi:"protected"`
	// Number of read-only replicas in the set (1 or 2)
	ReplicaCount *int `pulumi:"replicaCount"`
	// Current status of the read-only replica set
	Status *string `pulumi:"status"`
	// Last modification timestamp
	UpdatedAt *string `pulumi:"updatedAt"`
}

type ManagedClusterReplicasetState struct {
	// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
	ClusterId pulumi.StringPtrInput
	// Creation timestamp
	CreatedAt pulumi.StringPtrInput
	// ID of the project that owns the parent managed cluster
	ProjectId pulumi.StringPtrInput
	// Protection from accidental deletion. Delete is rejected by the API while this is true.
	Protected pulumi.BoolPtrInput
	// Number of read-only replicas in the set (1 or 2)
	ReplicaCount pulumi.IntPtrInput
	// Current status of the read-only replica set
	Status pulumi.StringPtrInput
	// Last modification timestamp
	UpdatedAt pulumi.StringPtrInput
}

func (ManagedClusterReplicasetState) ElementType() reflect.Type {
	return reflect.TypeOf((*managedClusterReplicasetState)(nil)).Elem()
}

type managedClusterReplicasetArgs struct {
	// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
	ClusterId string `pulumi:"clusterId"`
	// ID of the project that owns the parent managed cluster
	ProjectId string `pulumi:"projectId"`
	// Protection from accidental deletion. Delete is rejected by the API while this is true.
	Protected *bool `pulumi:"protected"`
	// Number of read-only replicas in the set (1 or 2)
	ReplicaCount int `pulumi:"replicaCount"`
}

// The set of arguments for constructing a ManagedClusterReplicaset resource.
type ManagedClusterReplicasetArgs struct {
	// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
	ClusterId pulumi.StringInput
	// ID of the project that owns the parent managed cluster
	ProjectId pulumi.StringInput
	// Protection from accidental deletion. Delete is rejected by the API while this is true.
	Protected pulumi.BoolPtrInput
	// Number of read-only replicas in the set (1 or 2)
	ReplicaCount pulumi.IntInput
}

func (ManagedClusterReplicasetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*managedClusterReplicasetArgs)(nil)).Elem()
}

type ManagedClusterReplicasetInput interface {
	pulumi.Input

	ToManagedClusterReplicasetOutput() ManagedClusterReplicasetOutput
	ToManagedClusterReplicasetOutputWithContext(ctx context.Context) ManagedClusterReplicasetOutput
}

func (*ManagedClusterReplicaset) ElementType() reflect.Type {
	return reflect.TypeOf((**ManagedClusterReplicaset)(nil)).Elem()
}

func (i *ManagedClusterReplicaset) ToManagedClusterReplicasetOutput() ManagedClusterReplicasetOutput {
	return i.ToManagedClusterReplicasetOutputWithContext(context.Background())
}

func (i *ManagedClusterReplicaset) ToManagedClusterReplicasetOutputWithContext(ctx context.Context) ManagedClusterReplicasetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ManagedClusterReplicasetOutput)
}

// ManagedClusterReplicasetArrayInput is an input type that accepts ManagedClusterReplicasetArray and ManagedClusterReplicasetArrayOutput values.
// You can construct a concrete instance of `ManagedClusterReplicasetArrayInput` via:
//
//	ManagedClusterReplicasetArray{ ManagedClusterReplicasetArgs{...} }
type ManagedClusterReplicasetArrayInput interface {
	pulumi.Input

	ToManagedClusterReplicasetArrayOutput() ManagedClusterReplicasetArrayOutput
	ToManagedClusterReplicasetArrayOutputWithContext(context.Context) ManagedClusterReplicasetArrayOutput
}

type ManagedClusterReplicasetArray []ManagedClusterReplicasetInput

func (ManagedClusterReplicasetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ManagedClusterReplicaset)(nil)).Elem()
}

func (i ManagedClusterReplicasetArray) ToManagedClusterReplicasetArrayOutput() ManagedClusterReplicasetArrayOutput {
	return i.ToManagedClusterReplicasetArrayOutputWithContext(context.Background())
}

func (i ManagedClusterReplicasetArray) ToManagedClusterReplicasetArrayOutputWithContext(ctx context.Context) ManagedClusterReplicasetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ManagedClusterReplicasetArrayOutput)
}

// ManagedClusterReplicasetMapInput is an input type that accepts ManagedClusterReplicasetMap and ManagedClusterReplicasetMapOutput values.
// You can construct a concrete instance of `ManagedClusterReplicasetMapInput` via:
//
//	ManagedClusterReplicasetMap{ "key": ManagedClusterReplicasetArgs{...} }
type ManagedClusterReplicasetMapInput interface {
	pulumi.Input

	ToManagedClusterReplicasetMapOutput() ManagedClusterReplicasetMapOutput
	ToManagedClusterReplicasetMapOutputWithContext(context.Context) ManagedClusterReplicasetMapOutput
}

type ManagedClusterReplicasetMap map[string]ManagedClusterReplicasetInput

func (ManagedClusterReplicasetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ManagedClusterReplicaset)(nil)).Elem()
}

func (i ManagedClusterReplicasetMap) ToManagedClusterReplicasetMapOutput() ManagedClusterReplicasetMapOutput {
	return i.ToManagedClusterReplicasetMapOutputWithContext(context.Background())
}

func (i ManagedClusterReplicasetMap) ToManagedClusterReplicasetMapOutputWithContext(ctx context.Context) ManagedClusterReplicasetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ManagedClusterReplicasetMapOutput)
}

type ManagedClusterReplicasetOutput struct{ *pulumi.OutputState }

func (ManagedClusterReplicasetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ManagedClusterReplicaset)(nil)).Elem()
}

func (o ManagedClusterReplicasetOutput) ToManagedClusterReplicasetOutput() ManagedClusterReplicasetOutput {
	return o
}

func (o ManagedClusterReplicasetOutput) ToManagedClusterReplicasetOutputWithContext(ctx context.Context) ManagedClusterReplicasetOutput {
	return o
}

// ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
func (o ManagedClusterReplicasetOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// Creation timestamp
func (o ManagedClusterReplicasetOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// ID of the project that owns the parent managed cluster
func (o ManagedClusterReplicasetOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Protection from accidental deletion. Delete is rejected by the API while this is true.
func (o ManagedClusterReplicasetOutput) Protected() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.BoolPtrOutput { return v.Protected }).(pulumi.BoolPtrOutput)
}

// Number of read-only replicas in the set (1 or 2)
func (o ManagedClusterReplicasetOutput) ReplicaCount() pulumi.IntOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.IntOutput { return v.ReplicaCount }).(pulumi.IntOutput)
}

// Current status of the read-only replica set
func (o ManagedClusterReplicasetOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Last modification timestamp
func (o ManagedClusterReplicasetOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ManagedClusterReplicaset) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type ManagedClusterReplicasetArrayOutput struct{ *pulumi.OutputState }

func (ManagedClusterReplicasetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ManagedClusterReplicaset)(nil)).Elem()
}

func (o ManagedClusterReplicasetArrayOutput) ToManagedClusterReplicasetArrayOutput() ManagedClusterReplicasetArrayOutput {
	return o
}

func (o ManagedClusterReplicasetArrayOutput) ToManagedClusterReplicasetArrayOutputWithContext(ctx context.Context) ManagedClusterReplicasetArrayOutput {
	return o
}

func (o ManagedClusterReplicasetArrayOutput) Index(i pulumi.IntInput) ManagedClusterReplicasetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ManagedClusterReplicaset {
		return vs[0].([]*ManagedClusterReplicaset)[vs[1].(int)]
	}).(ManagedClusterReplicasetOutput)
}

type ManagedClusterReplicasetMapOutput struct{ *pulumi.OutputState }

func (ManagedClusterReplicasetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ManagedClusterReplicaset)(nil)).Elem()
}

func (o ManagedClusterReplicasetMapOutput) ToManagedClusterReplicasetMapOutput() ManagedClusterReplicasetMapOutput {
	return o
}

func (o ManagedClusterReplicasetMapOutput) ToManagedClusterReplicasetMapOutputWithContext(ctx context.Context) ManagedClusterReplicasetMapOutput {
	return o
}

func (o ManagedClusterReplicasetMapOutput) MapIndex(k pulumi.StringInput) ManagedClusterReplicasetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ManagedClusterReplicaset {
		return vs[0].(map[string]*ManagedClusterReplicaset)[vs[1].(string)]
	}).(ManagedClusterReplicasetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ManagedClusterReplicasetInput)(nil)).Elem(), &ManagedClusterReplicaset{})
	pulumi.RegisterInputType(reflect.TypeOf((*ManagedClusterReplicasetArrayInput)(nil)).Elem(), ManagedClusterReplicasetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ManagedClusterReplicasetMapInput)(nil)).Elem(), ManagedClusterReplicasetMap{})
	pulumi.RegisterOutputType(ManagedClusterReplicasetOutput{})
	pulumi.RegisterOutputType(ManagedClusterReplicasetArrayOutput{})
	pulumi.RegisterOutputType(ManagedClusterReplicasetMapOutput{})
}
