// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kurrentcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/kurrent-io/pulumi-kurrentcloud/sdk/go/kurrentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the kurrentcloud package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	ClientId            pulumi.StringOutput    `pulumi:"clientId"`
	ClientSecret        pulumi.StringPtrOutput `pulumi:"clientSecret"`
	IdentityKitUrl      pulumi.StringPtrOutput `pulumi:"identityKitUrl"`
	IdentityProviderUrl pulumi.StringOutput    `pulumi:"identityProviderUrl"`
	OrganizationId      pulumi.StringOutput    `pulumi:"organizationId"`
	Token               pulumi.StringOutput    `pulumi:"token"`
	TokenStore          pulumi.StringOutput    `pulumi:"tokenStore"`
	Url                 pulumi.StringOutput    `pulumi:"url"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.IdentityProviderUrl == nil {
		return nil, errors.New("invalid value for required argument 'IdentityProviderUrl'")
	}
	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	if args.Token == nil {
		return nil, errors.New("invalid value for required argument 'Token'")
	}
	if args.TokenStore == nil {
		return nil, errors.New("invalid value for required argument 'TokenStore'")
	}
	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringPtrInput)
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:kurrentcloud", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	ClientId            string  `pulumi:"clientId"`
	ClientSecret        *string `pulumi:"clientSecret"`
	IdentityKitUrl      *string `pulumi:"identityKitUrl"`
	IdentityProviderUrl string  `pulumi:"identityProviderUrl"`
	OrganizationId      string  `pulumi:"organizationId"`
	Token               string  `pulumi:"token"`
	TokenStore          string  `pulumi:"tokenStore"`
	Url                 string  `pulumi:"url"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	ClientId            pulumi.StringInput
	ClientSecret        pulumi.StringPtrInput
	IdentityKitUrl      pulumi.StringPtrInput
	IdentityProviderUrl pulumi.StringInput
	OrganizationId      pulumi.StringInput
	Token               pulumi.StringInput
	TokenStore          pulumi.StringInput
	Url                 pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func (o ProviderOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

func (o ProviderOutput) ClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientSecret }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) IdentityKitUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.IdentityKitUrl }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) IdentityProviderUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.IdentityProviderUrl }).(pulumi.StringOutput)
}

func (o ProviderOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o ProviderOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

func (o ProviderOutput) TokenStore() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.TokenStore }).(pulumi.StringOutput)
}

func (o ProviderOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
