# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ManagedClusterReplicasetArgs', 'ManagedClusterReplicaset']

@pulumi.input_type
class ManagedClusterReplicasetArgs:
    def __init__(__self__, *,
                 cluster_id: pulumi.Input[str],
                 project_id: pulumi.Input[str],
                 replica_count: pulumi.Input[int],
                 protected: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a ManagedClusterReplicaset resource.
        :param pulumi.Input[str] cluster_id: ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        :param pulumi.Input[str] project_id: ID of the project that owns the parent managed cluster
        :param pulumi.Input[int] replica_count: Number of read-only replicas in the set (1 or 2)
        :param pulumi.Input[bool] protected: Protection from accidental deletion. Delete is rejected by the API while this is true.
        """
        pulumi.set(__self__, "cluster_id", cluster_id)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "replica_count", replica_count)
        if protected is not None:
            pulumi.set(__self__, "protected", protected)

    @property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[str]:
        """
        ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        """
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "cluster_id", value)

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[str]:
        """
        ID of the project that owns the parent managed cluster
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "project_id", value)

    @property
    @pulumi.getter(name="replicaCount")
    def replica_count(self) -> pulumi.Input[int]:
        """
        Number of read-only replicas in the set (1 or 2)
        """
        return pulumi.get(self, "replica_count")

    @replica_count.setter
    def replica_count(self, value: pulumi.Input[int]):
        pulumi.set(self, "replica_count", value)

    @property
    @pulumi.getter
    def protected(self) -> Optional[pulumi.Input[bool]]:
        """
        Protection from accidental deletion. Delete is rejected by the API while this is true.
        """
        return pulumi.get(self, "protected")

    @protected.setter
    def protected(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "protected", value)


@pulumi.input_type
class _ManagedClusterReplicasetState:
    def __init__(__self__, *,
                 cluster_id: Optional[pulumi.Input[str]] = None,
                 created_at: Optional[pulumi.Input[str]] = None,
                 project_id: Optional[pulumi.Input[str]] = None,
                 protected: Optional[pulumi.Input[bool]] = None,
                 replica_count: Optional[pulumi.Input[int]] = None,
                 status: Optional[pulumi.Input[str]] = None,
                 updated_at: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering ManagedClusterReplicaset resources.
        :param pulumi.Input[str] cluster_id: ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        :param pulumi.Input[str] created_at: Creation timestamp
        :param pulumi.Input[str] project_id: ID of the project that owns the parent managed cluster
        :param pulumi.Input[bool] protected: Protection from accidental deletion. Delete is rejected by the API while this is true.
        :param pulumi.Input[int] replica_count: Number of read-only replicas in the set (1 or 2)
        :param pulumi.Input[str] status: Current status of the read-only replica set
        :param pulumi.Input[str] updated_at: Last modification timestamp
        """
        if cluster_id is not None:
            pulumi.set(__self__, "cluster_id", cluster_id)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if protected is not None:
            pulumi.set(__self__, "protected", protected)
        if replica_count is not None:
            pulumi.set(__self__, "replica_count", replica_count)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        """
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "cluster_id", value)

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[pulumi.Input[str]]:
        """
        Creation timestamp
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "created_at", value)

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the project that owns the parent managed cluster
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "project_id", value)

    @property
    @pulumi.getter
    def protected(self) -> Optional[pulumi.Input[bool]]:
        """
        Protection from accidental deletion. Delete is rejected by the API while this is true.
        """
        return pulumi.get(self, "protected")

    @protected.setter
    def protected(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "protected", value)

    @property
    @pulumi.getter(name="replicaCount")
    def replica_count(self) -> Optional[pulumi.Input[int]]:
        """
        Number of read-only replicas in the set (1 or 2)
        """
        return pulumi.get(self, "replica_count")

    @replica_count.setter
    def replica_count(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "replica_count", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[str]]:
        """
        Current status of the read-only replica set
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "status", value)

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[pulumi.Input[str]]:
        """
        Last modification timestamp
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "updated_at", value)


class ManagedClusterReplicaset(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_id: Optional[pulumi.Input[str]] = None,
                 project_id: Optional[pulumi.Input[str]] = None,
                 protected: Optional[pulumi.Input[bool]] = None,
                 replica_count: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        """
        Create a ManagedClusterReplicaset resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] cluster_id: ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        :param pulumi.Input[str] project_id: ID of the project that owns the parent managed cluster
        :param pulumi.Input[bool] protected: Protection from accidental deletion. Delete is rejected by the API while this is true.
        :param pulumi.Input[int] replica_count: Number of read-only replicas in the set (1 or 2)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ManagedClusterReplicasetArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ManagedClusterReplicaset resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ManagedClusterReplicasetArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ManagedClusterReplicasetArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_id: Optional[pulumi.Input[str]] = None,
                 project_id: Optional[pulumi.Input[str]] = None,
                 protected: Optional[pulumi.Input[bool]] = None,
                 replica_count: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ManagedClusterReplicasetArgs.__new__(ManagedClusterReplicasetArgs)

            if cluster_id is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_id'")
            __props__.__dict__["cluster_id"] = cluster_id
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["protected"] = protected
            if replica_count is None and not opts.urn:
                raise TypeError("Missing required property 'replica_count'")
            __props__.__dict__["replica_count"] = replica_count
            __props__.__dict__["created_at"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
        super(ManagedClusterReplicaset, __self__).__init__(
            'kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            cluster_id: Optional[pulumi.Input[str]] = None,
            created_at: Optional[pulumi.Input[str]] = None,
            project_id: Optional[pulumi.Input[str]] = None,
            protected: Optional[pulumi.Input[bool]] = None,
            replica_count: Optional[pulumi.Input[int]] = None,
            status: Optional[pulumi.Input[str]] = None,
            updated_at: Optional[pulumi.Input[str]] = None) -> 'ManagedClusterReplicaset':
        """
        Get an existing ManagedClusterReplicaset resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] cluster_id: ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        :param pulumi.Input[str] created_at: Creation timestamp
        :param pulumi.Input[str] project_id: ID of the project that owns the parent managed cluster
        :param pulumi.Input[bool] protected: Protection from accidental deletion. Delete is rejected by the API while this is true.
        :param pulumi.Input[int] replica_count: Number of read-only replicas in the set (1 or 2)
        :param pulumi.Input[str] status: Current status of the read-only replica set
        :param pulumi.Input[str] updated_at: Last modification timestamp
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ManagedClusterReplicasetState.__new__(_ManagedClusterReplicasetState)

        __props__.__dict__["cluster_id"] = cluster_id
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["protected"] = protected
        __props__.__dict__["replica_count"] = replica_count
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        return ManagedClusterReplicaset(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Output[str]:
        """
        ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
        """
        return pulumi.get(self, "cluster_id")

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[str]:
        """
        Creation timestamp
        """
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[str]:
        """
        ID of the project that owns the parent managed cluster
        """
        return pulumi.get(self, "project_id")

    @property
    @pulumi.getter
    def protected(self) -> pulumi.Output[Optional[bool]]:
        """
        Protection from accidental deletion. Delete is rejected by the API while this is true.
        """
        return pulumi.get(self, "protected")

    @property
    @pulumi.getter(name="replicaCount")
    def replica_count(self) -> pulumi.Output[int]:
        """
        Number of read-only replicas in the set (1 or 2)
        """
        return pulumi.get(self, "replica_count")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[str]:
        """
        Current status of the read-only replica set
        """
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[str]:
        """
        Last modification timestamp
        """
        return pulumi.get(self, "updated_at")

