// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/kurrent-io/pulumi-kurrentcloud/sdk/go/kurrentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "kurrentcloud:clientId")
}
func GetIdentityProviderUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "kurrentcloud:identityProviderUrl")
}
func GetOrganizationId(ctx *pulumi.Context) string {
	return config.Get(ctx, "kurrentcloud:organizationId")
}
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "kurrentcloud:token")
}
func GetTokenStore(ctx *pulumi.Context) string {
	return config.Get(ctx, "kurrentcloud:tokenStore")
}
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "kurrentcloud:url")
}
